const fs = require('fs');
const path = require('path');
const readline = require('readline');

const ENV_PATH = path.join(__dirname, '.env');
const PING_ENDPOINTS = [
  { path: '/auth/v1/health', label: 'auth health' },
  { path: '/rest/v1/', label: 'rest api' },
];

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl, question, { defaultAnswer = '' } = {}) {
  const suffix = defaultAnswer ? ` [${defaultAnswer}]` : '';

  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultAnswer);
    });
  });
}

function askYesNo(rl, question, defaultYes = true) {
  const hint = defaultYes ? 'Y/n' : 'y/N';

  return new Promise((resolve) => {
    rl.question(`${question} (${hint}): `, (answer) => {
      const normalized = answer.trim().toLowerCase();

      if (!normalized) {
        resolve(defaultYes);
        return;
      }

      resolve(normalized === 'y' || normalized === 'yes');
    });
  });
}

function askSecret(rl, question) {
  if (!process.stdin.isTTY) {
    return ask(rl, question);
  }

  return new Promise((resolve) => {
    const stdin = process.stdin;
    let input = '';

    rl.pause();
    process.stdout.write(`${question}: `);

    stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding('utf8');

    const onData = (char) => {
      switch (char) {
        case '\n':
        case '\r':
        case '\u0004':
          stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener('data', onData);
          process.stdout.write('\n');
          resolve(input.trim());
          break;
        case '\u0003':
          process.stdout.write('\n');
          process.exit(130);
          break;
        case '\u007f':
          input = input.slice(0, -1);
          readline.clearLine(process.stdout, 0);
          readline.cursorTo(process.stdout, question.length + 2);
          break;
        default:
          if (char >= ' ') {
            input += char;
            process.stdout.write('*');
          }
          break;
      }
    };

    stdin.on('data', onData);
  });
}

function normalizeUrl(url) {
  return url.replace(/\/+$/, '');
}

function isValidSupabaseUrl(url) {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'https:' && parsed.hostname.endsWith('.supabase.co');
  } catch {
    return false;
  }
}

function formatEnv(projects) {
  if (projects.length === 1) {
    const project = projects[0];
    const lines = [
      '# Generated by setup.js',
      `NEXT_PUBLIC_SUPABASE_URL=${project.url}`,
      `NEXT_PUBLIC_SUPABASE_ANON_KEY=${project.apiKey}`,
      `SUPABASE_PROJECT_NAME=${project.name}`,
      '',
    ];

    return lines.join('\n');
  }

  const payload = JSON.stringify(
    projects.map((project) => ({
      name: project.name,
      url: project.url,
      anonKey: project.apiKey,
    }))
  );

  return ['# Generated by setup.js', `SUPABASE_PROJECTS=${payload}`, ''].join('\n');
}

async function testProject(project) {
  for (const endpoint of PING_ENDPOINTS) {
    try {
      const response = await fetch(`${project.url}${endpoint.path}`, {
        headers: {
          apikey: project.apiKey,
          Authorization: `Bearer ${project.apiKey}`,
        },
      });

      if (response.ok) {
        return { ok: true, detail: `${endpoint.label} (HTTP ${response.status})` };
      }
    } catch {
      // Try the next endpoint.
    }
  }

  return { ok: false, detail: 'all ping methods failed' };
}

async function collectProject(rl, index) {
  console.log(`\nProject ${index + 1}`);

  const defaultName = `project-${index + 1}`;
  const name = await ask(rl, '  Name', { defaultAnswer: defaultName });

  let url = '';
  while (!url) {
    const answer = await ask(rl, '  Project URL (https://your-ref.supabase.co)');
    const normalized = normalizeUrl(answer);

    if (isValidSupabaseUrl(normalized)) {
      url = normalized;
      continue;
    }

    console.log('  Enter a valid https://*.supabase.co URL.');
  }

  let apiKey = '';
  while (!apiKey) {
    apiKey = await askSecret(rl, '  Anon key (hidden input)');

    if (!apiKey) {
      console.log('  API key is required.');
    }
  }

  return { name, url, apiKey };
}

async function main() {
  const rl = createInterface();

  console.log('Supabase Pause Prevention - Setup\n');
  console.log('This wizard creates a .env file for keeping free-tier projects active.');
  console.log('Find your project URL and anon key in:');
  console.log('Supabase Dashboard -> Project Settings -> API\n');

  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await askYesNo(rl, '.env already exists. Overwrite it?', false);

    if (!overwrite) {
      console.log('Setup cancelled. Existing .env was left unchanged.');
      rl.close();
      return;
    }
  }

  const projects = [];

  do {
    projects.push(await collectProject(rl, projects.length));
  } while (await askYesNo(rl, '\nAdd another project?', false));

  console.log('\nConfigured projects:');
  for (const project of projects) {
    console.log(`  - ${project.name}: ${project.url}`);
  }

  const shouldTest = await askYesNo(rl, '\nTest connections now?', true);

  if (shouldTest) {
    console.log('');

    for (const project of projects) {
      process.stdout.write(`  Testing ${project.name}... `);
      const result = await testProject(project);
      console.log(result.ok ? `ok (${result.detail})` : `failed (${result.detail})`);
    }
  }

  const shouldWrite = await askYesNo(rl, '\nWrite .env file?', true);

  if (!shouldWrite) {
    console.log('Setup cancelled. No files were written.');
    rl.close();
    return;
  }

  fs.writeFileSync(ENV_PATH, formatEnv(projects), 'utf8');

  console.log(`\nWrote ${ENV_PATH}`);
  console.log('Start the keep-alive process with: npm start');

  rl.close();
}

main().catch((error) => {
  console.error('\nSetup failed:', error.message);
  process.exit(1);
});
