const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { DEFAULT_TABLE, ensureKeepaliveTable, loadSql } = require('./keepalive');
const { normalizeUrl, pingTable, pingProject } = require('./ping');

const ENV_PATH = path.join(__dirname, '.env');

function createInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl, question, { defaultAnswer = '' } = {}) {
  const suffix = defaultAnswer ? ` [${defaultAnswer}]` : '';

  return new Promise((resolve) => {
    rl.question(`${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultAnswer);
    });
  });
}

function askYesNo(rl, question, defaultYes = true) {
  const hint = defaultYes ? 'Y/n' : 'y/N';

  return new Promise((resolve) => {
    rl.question(`${question} (${hint}): `, (answer) => {
      const normalized = answer.trim().toLowerCase();

      if (!normalized) {
        resolve(defaultYes);
        return;
      }

      resolve(normalized === 'y' || normalized === 'yes');
    });
  });
}

function askSecret(rl, question) {
  if (!process.stdin.isTTY) {
    return ask(rl, question);
  }

  return new Promise((resolve) => {
    const stdin = process.stdin;
    let input = '';

    rl.pause();
    process.stdout.write(`${question}: `);

    stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding('utf8');

    const onData = (char) => {
      switch (char) {
        case '\n':
        case '\r':
        case '\u0004':
          stdin.setRawMode(false);
          stdin.pause();
          stdin.removeListener('data', onData);
          process.stdout.write('\n');
          resolve(input.trim());
          break;
        case '\u0003':
          process.stdout.write('\n');
          process.exit(130);
          break;
        case '\u007f':
          input = input.slice(0, -1);
          readline.clearLine(process.stdout, 0);
          readline.cursorTo(process.stdout, question.length + 2);
          break;
        default:
          if (char >= ' ') {
            input += char;
            process.stdout.write('*');
          }
          break;
      }
    };

    stdin.on('data', onData);
  });
}

function isValidSupabaseUrl(url) {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'https:' && parsed.hostname.endsWith('.supabase.co');
  } catch {
    return false;
  }
}

function formatProjectEntry(project) {
  const entry = {
    name: project.name,
    url: project.url,
    anonKey: project.apiKey,
  };

  if (project.serviceRoleKey) {
    entry.serviceRoleKey = project.serviceRoleKey;
  }

  if (project.table && project.table !== DEFAULT_TABLE) {
    entry.table = project.table;
  }

  return entry;
}

function formatEnv(projects) {
  if (projects.length === 1) {
    const project = projects[0];
    const lines = [
      '# Generated by setup.js',
      `NEXT_PUBLIC_SUPABASE_URL=${project.url}`,
      `NEXT_PUBLIC_SUPABASE_ANON_KEY=${project.apiKey}`,
      `SUPABASE_PROJECT_NAME=${project.name}`,
    ];

    if (project.serviceRoleKey) {
      lines.push(`SUPABASE_SERVICE_ROLE_KEY=${project.serviceRoleKey}`);
    }

    if (project.table && project.table !== DEFAULT_TABLE) {
      lines.push(`SUPABASE_TABLE=${project.table}`);
    }

    lines.push('');
    return lines.join('\n');
  }

  const payload = JSON.stringify(projects.map(formatProjectEntry));

  return ['# Generated by setup.js', `SUPABASE_PROJECTS=${payload}`, ''].join('\n');
}

async function setupKeepaliveTable(rl, project) {
  if (project.table !== DEFAULT_TABLE) {
    console.log(`  ${project.name}: using custom table "${project.table}" — skipping auto-setup`);
    return;
  }

  const existing = await pingTable(project);
  if (existing.ok) {
    console.log(`  ${project.name}: _keepalive table already exists`);
    return;
  }

  const shouldMigrate = await askYesNo(
    rl,
    `  ${project.name}: create _keepalive table automatically?`,
    true
  );

  if (!shouldMigrate) {
    console.log(`  ${project.name}: skipped — paste sql/keepalive.sql in the SQL Editor instead`);
    return;
  }

  const databasePassword = await askSecret(
    rl,
    `  ${project.name} database password (Dashboard -> Settings -> Database)`
  );

  if (!databasePassword) {
    console.log(`  ${project.name}: skipped — no database password provided`);
    return;
  }

  process.stdout.write(`  ${project.name}: creating _keepalive table... `);

  try {
    await ensureKeepaliveTable(project.url, databasePassword);
    console.log('ok');
  } catch (error) {
    console.log(`failed (${error.message})`);

    if (error.message.includes('ENOTFOUND') || error.message.includes('getaddrinfo')) {
      console.log('    The project may be paused — unpause it in the dashboard and re-run setup.');
    }
  }
}

async function collectProject(rl, index) {
  console.log(`\nProject ${index + 1}`);

  const defaultName = `project-${index + 1}`;
  const name = await ask(rl, '  Name', { defaultAnswer: defaultName });

  let url = '';
  while (!url) {
    const answer = await ask(rl, '  Project URL (https://your-ref.supabase.co)');
    const normalized = normalizeUrl(answer);

    if (isValidSupabaseUrl(normalized)) {
      url = normalized;
      continue;
    }

    console.log('  Enter a valid https://*.supabase.co URL.');
  }

  let apiKey = '';
  while (!apiKey) {
    apiKey = await askSecret(rl, '  Anon key (hidden input)');

    if (!apiKey) {
      console.log('  API key is required.');
    }
  }

  const serviceRoleKey = await askSecret(
    rl,
    '  Service role key (optional, hidden — enables auth admin fallback)'
  );

  const table = await ask(rl, '  Keep-alive table', { defaultAnswer: DEFAULT_TABLE });

  return { name, url, apiKey, serviceRoleKey, table };
}

async function main() {
  const rl = createInterface();

  console.log('Supabase Pause Prevention - Setup\n');
  console.log('This wizard creates a .env file for keeping free-tier projects active.');
  console.log('Find your project URL and keys in:');
  console.log('Supabase Dashboard -> Project Settings -> API\n');
  console.log('Setup creates a _keepalive table automatically using each project\'s');
  console.log('database password (Dashboard -> Settings -> Database).\n');

  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await askYesNo(rl, '.env already exists. Overwrite it?', false);

    if (!overwrite) {
      console.log('Setup cancelled. Existing .env was left unchanged.');
      rl.close();
      return;
    }
  }

  const projects = [];

  do {
    projects.push(await collectProject(rl, projects.length));
  } while (await askYesNo(rl, '\nAdd another project?', false));

  console.log('\nConfigured projects:');
  for (const project of projects) {
    console.log(`  - ${project.name}: ${project.url}`);
  }

  const shouldSetupTables = await askYesNo(rl, '\nSet up _keepalive tables now?', true);

  if (shouldSetupTables) {
    console.log('');

    for (const project of projects) {
      await setupKeepaliveTable(rl, project);
    }
  } else {
    console.log('\nSkipped table setup. Run sql/keepalive.sql manually in each project:\n');
    console.log(loadSql());
  }

  const shouldTest = await askYesNo(rl, '\nTest connections now?', true);

  if (shouldTest) {
    console.log('');

    for (const project of projects) {
      process.stdout.write(`  Testing ${project.name}... `);
      const result = await pingProject(project);
      console.log(result.ok ? `ok (${result.detail})` : `failed (${result.detail})`);
    }
  }

  const shouldWrite = await askYesNo(rl, '\nWrite .env file?', true);

  if (!shouldWrite) {
    console.log('Setup cancelled. No files were written.');
    rl.close();
    return;
  }

  fs.writeFileSync(ENV_PATH, formatEnv(projects), 'utf8');

  console.log(`\nWrote ${ENV_PATH}`);
  console.log('\nNext steps:');
  console.log('1. Unpause any paused projects in the Supabase dashboard');
  console.log('2. Test: npm run ping');
  console.log('3. Start with PM2: pm2 start npm --name supabase-keepalive -- start');

  rl.close();
}

main().catch((error) => {
  console.error('\nSetup failed:', error.message);
  process.exit(1);
});
